server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: bankAccountModule
        uri: http://localhost:8081/
        predicates:
        - Path=/account/**
      - id: bankTransfertModule
        uri: http://localhost:8082/
        predicates:
        - Path=/transfert/**
      - id: authentificationModule
        uri: http://localhost:8083/
        predicates:
        - Path=/customer/**